layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 3
  exclude:
    archived: false
    forks: false

social_media:
  telegram: k0t3n
  instagram: k0t3n
  twitter: k0t3n
  vk: k0t3n
  linkedin: k0t3n
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # unsplash: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png

  - name: Django
    web_url: https://github.com/topics/django
    image_url: http://sharelink.ru/media/uploads/blazer/2018/04/23/django-logo.png

  - name: devops
    web_url: https://github.com/topics/devops
    image_url: https://cdn1.iconfinder.com/data/icons/devops-cycle/256/devops_cycle_1_filled-512.png
